### ISSUE TITLE
Mhercy

### ISSUE THREAD

**Issue by historia** [wwcodemanila/WWCodeManila-Python#17]
https://github.com/historia/wwcode

**Comment by neequole** [comment]
Good job! Some suggestions below :)

[Exercise1](https://github.com/historia/wwcode/blob/master/mcbarbosa_excercise_1.py)
* We need to anticipate amounts with decimal (e.g 150.5) - maybe we can use `float` instead of `int`?
`change = int(payment) - int(total_bill)`
* If we want to specify the no. decimal places, we can use `round()` or [formatting](https://stackoverflow.com/questions/455612/limiting-floats-to-two-decimal-points) 

[Exercise2](https://github.com/historia/wwcode/blob/master/mcbarbosa_exercise2.py)
* As per last presentation, we can also utilize string indexing to avoid hardcoding the index
`name = '{} {} {}'.format(break_data[1], break_data[2], break_data[3])` -> `data[1:-1]`
