### ISSUE TITLE
sampaco_exercise1

### ISSUE THREAD

**Issue by ghost** [wwcodemanila/WWCodeManila-Python#21]
https://repl.it/JSpZ/0

**Comment by alyssonalvaran** [comment]
Hello!

- First of all, it's awesome how you finished the challenge with just 3 lines of codes. Kudos on keeping it simple and straight to the point.

- Good job on converting your user's inputs (which is `string` by default) into `int` to enable arithmetic operations. Taking this a step further, maybe you can use `float` instead so they can enter decimal numbers as well (since the challenge is about payments and bills).

- Lastly, I noticed that you used string substitution (e.g. `"{}".format(variable)`) in printing your string. Fun fact: String concatenation (e.g. `"string " + variable`) is actually faster in terms of performance compared to string substitution and is therefore recommended if you're creating large systems. String substitution, on the other hand, is more stylish and readable, which is also something to consider if you prefer readability over performance. Ultimately, both formats are correct and choosing what format to use is always up to you. ;)

I hope you had fun last time. See you again next meetup!
