### ISSUE TITLE
mgsranoa - Loops

### ISSUE THREAD

**Issue by iammodmod** [wwcodemanila/WWCodeManila-Python#25]
For Python Loops Topic:
https://github.com/iammodmod/wwcode-python/blob/master/loops01.py

**Comment by alyssonalvaran** [comment]
Hello!

Awesome job on finishing the challenge on loops. Here's my code review:

- +1 for creating a `compute` function which returns the sum of the `cash_on_vault` and the number of `bills`. Do you have prior programming experience? You seem well-versed with functions and dictionaries already. :)

- Another way to get the sum of the elements inside `cash_on_vault` is by using Python's built-in `sum` function which gets the sum of a list of elements. Although your approach is good and working as it is, I recommend that you familiarize yourself with and make the most out of Python's simple but really helpful built-in functions.

- Instead of assigning your variables with floating point values (`bills = 0.00`) and reusing them later by assigning another value, a better practice would be to use the `float()` function to convert the values and thus eliminate the need for unnecessary variable assignments.

- Lastly, since we're computing money for this challenge, it'd be nice if you display the output with two decimal places instead of Python's default one decimal place.

By the way, there's a declared variable in your code named `coins` that was never used. ;)

Here's the modified version of your code where I applied the recommendations stated above:

```
def compute(list_of_money):
    bills = 0
    for money in list_of_money:
        if not is_coins(money):
            bills += money

    return {
      'income':float(sum(list_of_money)),
      'bills':float(bills)
    }

cash_on_vault = [1, 5, 100, 10, 50, 50, 20, 5, 1, 1000, 1000, 500, 5, 200]
return_value = compute(cash_on_vault)

print(f"Aling Nena's Total income: {return_value['income']:.2f}")
print(f"Aling Nena's Total Amount of Bills: {return_value['bills']:.2f}")
```

**Bonus**: I happen to be reading about Python formatters while reviewing your code so here's a couple of links you might find useful:
- Python String Format Cookbook by Marcus Kazmierczak: https://mkaz.tech/code/python-string-format-cookbook/
- PyFormat by Ulrich Petri and Will McCutchen: https://pyformat.info/

Let me know if you have any questions or suggestions. I hope you had during last time. See you again next meetup!
