### ISSUE TITLE
OV - Functions

### ISSUE THREAD

**Issue by olynvalencia** [wwcodemanila/WWCodeManila-Python#26]
https://github.com/olynvalencia/wwcodemanila-python/blob/master/functions01.py

**Comment by alyssonalvaran** [comment]
Hello!

Congratulations on finishing the exercise on functions. You're almost done with the basic concepts of Python. Great job!

Just a couple of suggestions and recommendations:

- Since the converter function returns a specific amount of money and the list of keys in the dictionary referenced are in lowercase, it'll be more efficient to convert the input to lowercase inside the function as well as convert the output to float before returning it instead of repeatedly parsing it in your main code.

```
def converter(currency, amount):
    return float(amount * PHP_EXCHANGE_RATE[currency.lower()])
```

- While it's good to make the most out of functions, always remember that _functions are created for reusability and abstraction_. Therefore, trying to put everything inside a function and/or creating non-reusable functions is not really a good idea because it will just add to the number of lines of your code. Case in point: instead of putting your main code inside the `start` function and calling it outside, you can just directly put it outside. Also, **explicit is better than implicit** (Zen of Python).

- Avoid hard-coding lists. If, for example, Mang Toto decided to start converting AUD a couple of weeks from now, you will have to manually add AUD to the list of currencies accepted in your input question. You can do something like this instead:

`customer_currency = input("Welcome to Mang Toto's ForEx! What is your currency? We accept ({}): ".format((', '.join(PHP_EXCHANGE_RATE.keys())).upper())).upper()`

(I also converted the input value to uppercase in the example above so you won't have to repeatedly convert it to uppercase everytime you print it.)

- Lastly, although your first input question has been handled in case the user entered an invalid or unavailable currency, there's no exception handling in case the user entered an invalid amount (e.g. string - "abc"). You can use the `try `and `except ` keywords in this case.

```
try:
    customer_amt = float(input("How much {}?".format(customer_currency)))
    print("Your {:.02f} {} is equivalent to {:.02f} PHP.".format(customer_amt, customer_currency, converter(customer_currency, customer_amt)))
  except ValueError: 
      print("You've entered an invalid amount.")
```

There are a lot of other exceptions that we can still handle, but for now, it's enough make sure that the program will not unexpectedly stop while running.

- Here's the modified version of your code after I applied the suggestions stated above:

```
def converter(currency, amount):
    return float(amount * PHP_EXCHANGE_RATE[currency.lower()])

customer_currency = input("Welcome to Mang Toto's ForEx! What is your currency? We accept ({}): ".format((', '.join(PHP_EXCHANGE_RATE.keys())).upper())).upper()
if (customer_currency.lower() in PHP_EXCHANGE_RATE):
  try:
    customer_amt = float(input("How much {}?".format(customer_currency)))
    print("Your {:.02f} {} is equivalent to {:.02f} PHP.".format(customer_amt, customer_currency, converter(customer_currency, customer_amt)))
  except ValueError: 
      print("You've entered an invalid amount.")
else:
  print("Sorry! We do not exchange {}!".format(customer_currency))
```

Let me know if you have any comments or questions and I hope you had fun last time. See you next meetup! :)
