### ISSUE TITLE
wcfutalan - variables

### ISSUE THREAD

**Issue by wcfutalan** [wwcodemanila/WWCodeManila-Python#27]
https://github.com/wcfutalan/wwcode-python/blob/master/wcfutalan_exercise01.py

**Comment by neequole** [comment]
Hi,

Great job on:
* Following [PEP8](https://www.python.org/dev/peps/pep-0008/#naming-conventions) for naming variables, making its usage understandable :) Though I would recommend using `total_bill` instead of just `total`
* Converting the numbers to `float` instead of `int` w/c covers the case of bills with cents :)

If you are interested on limiting the number to certain decimal places, you can:
* [String formatting](https://stackoverflow.com/questions/455612/limiting-floats-to-two-decimal-points)

```python
print('Hi! Your change is: {:.2f}'.format(change))
```

* Use built-in function [round](https://docs.python.org/3/library/functions.html#round)

```python
print(Hi! Your change is: {}'.format(round(change, 2)))
```

Hope you enjoyed the session! See you next time :)
