### ISSUE TITLE
Samuel Oberes - Variables, Arithmetic Operations, Keyboard Input

### ISSUE THREAD

**Issue by samuel012** [wwcodemanila/WWCodeManila-Python#28]
https://github.com/samuel012/wwcode-python/blob/master/exercises01/sdoberes_exercise01.py

**Comment by alyssonalvaran** [comment]
Hi!

Congratulations on finishing the first exercise and welcome to WWCode Manila.

I actually don't have any comments with regards to your code. It's clean, simple, and easy to understand as it is. Just a couple of tips/suggestions:

- It may be beneficial in the long run to convert the each variable to float upon user input to avoid repeatedly converting it everytime you have to use it for computation (`total_bill = float(input('How much is your total bill? '))`).
- Another way to print the output is to directly compute inside the `print` statement (`print('Hi! Your change is {:.2f}'.format(payment - total_bill))`). The good thing about this approach is it lessens the number of variables declared and the total number lines, but I personally prefer your approach because it looks cleaner and more readable. ;)

That's it. I hope you had fun last time. See you next meetup!
