### ISSUE TITLE
Python exercises

### ISSUE THREAD

**Issue by octoberdearest** [wwcodemanila/WWCodeManila-Python#3]
https://github.com/octoberdearest/Python/blob/master/Exercise1_Number.py
https://github.com/octoberdearest/Python/blob/master/Exercise2.py

**Comment by neequole** [comment]
Good job!

**Exercise 1**
* for added info, we can also utilize `round()` or [formatting](https://stackoverflow.com/questions/455612/limiting-floats-to-two-decimal-points) to format the no. of decimal places.

**Exercise 2**
* We expect that reward #2 will be Boy Bawang
```shell
>> Please enter text: 2 nicole i tibay f
>> Hi Nicole I Tibay! You have successfully redeem reward #2 - 15pcs. Yucky candy! Thank you for using Aling Nena's Sari-sari store.
```
to fix this, maybe we can subtract 1 to the given input reward because array indexing starts at 0
```python
#reward_val = rewards[reward_num]
reward_val = rewards[reward_num-1]
```
* For added knowledge, we can also start indexing from last position by using negative no.
```python
# cust_name = entered_text[2:entered_text_len-2].title()
cust_name = entered_text[2:-2].title()
```
