### ISSUE TITLE
Samuel Oberes - Intro to PEP8, Strings

### ISSUE THREAD

**Issue by samuel012** [wwcodemanila/WWCodeManila-Python#30]
https://github.com/samuel012/wwcode-python/blob/master/exercises02/sdoberes_exercise02.py

**Comment by alyssonalvaran** [comment]
Hi!

Great job on finishing the second challenge. Here are my thoughts on your codes:

- Although splitting the user's input per non-breaking space may be the easiest approach to store the values that you need into a list, it's prone to errors because:

1. There are people with two or more first names. (e.g. Anna Marie)
2. Some people don't have a middle name.
3. Users may not enter their whole name at all, and just prefer to stick with their nicknames since it's not required, anyway.

In this case, assuming that the user will enter his/her input in this format: **<Reward number 1-9> <Customer’s name> <Gender f or m>**, you can try this approach instead :

```
reward_number = int(input_text[:1])
name = input_text[2:-2]
gender = input_text[-1:] # not actually necessary
```

By extracting the first and last characters of the string, which corresponds to the reward number and user's gender respectively, and storing the user's name in a single string, you won't have to worry about the number of words entered and proceed to printing the output like so:

`print(f'Hi {name.title()}! You have successfully redeemed reward #{reward_number} - {rewards[reward_number -1]}! Thank you for choosing Aling Nena\'s Sari-sari store.')`

One bug that this doesn't cover, however, is identifying whether the user entered a middle name, or a middle initial, and if the middle initial has a period or not. This is usually solved by changing the required format of the input or by asking for a series of inputs instead of a single one.

- Lastly, I'm assuming that you divided the output into two sentences for readability purposes since the expected output is a bit long. This resulted, however, into declaring two unnecessary variables. You can do something like this instead:

```
print('Hi {}! You have successfully redeemed reward #{} - {}! Thank you for choosing Aling Nena\'s Sari-sari store.'.format(
  name.title(), # user's name
  reward_number, # reward number chosen
  rewards[reward_number -1]) # corresponding reward item
)
```

Let me know if you have any questions or suggestions. See you next meetup!
