### ISSUE TITLE
Patricia Ilano - Exercise 1

### ISSUE THREAD

**Issue by ilanopat** [wwcodemanila/WWCodeManila-Python#34]
https://github.com/ilanopat/wwcode-exercises/blob/master/exercises01.py

**Comment by neequole** [comment]
Hi Patricia,

Great job on:
* Following [PEP8](https://www.python.org/dev/peps/pep-0008/#naming-conventions) for naming variables, making its usage understandable
* Converting the numbers to `float` instead of `int` w/c covers the case of bills with cents :)

If you are interested on limiting the number to certain decimal places, you can:
* [String formatting](https://stackoverflow.com/questions/455612/limiting-floats-to-two-decimal-points)

```python
print('Change is: {:.2f}'.format(change))
```

* Use built-in function [round](https://docs.python.org/3/library/functions.html#round)

```python
print('Change is: {}'.format(round(change, 2)))
```

Hope you enjoyed the session! See you next time :)
