### ISSUE TITLE
Marianelle Ebido - Variables, Arithmetic Operations, Keyboard Input

### ISSUE THREAD

**Issue by marianelleebido** [wwcodemanila/WWCodeManila-Python#36]
https://github.com/marianelleebido/wwcode-python/blob/master/mdebido_exercise01.py

**Comment by neequole** [comment]
Hi Marian,

Great job on:
* Naming the variables such that it its role can be understood
* Converting the numbers to `float` instead of `int` w/c covers the case of bills with cents :)

Just a few tip in case you want it to limit to certain decimal places:
* [String formatting](https://stackoverflow.com/questions/455612/limiting-floats-to-two-decimal-points)

```python
print('Hi! Your change is {:.2f}'.format(change))
```

* Use built-in function [round](https://docs.python.org/3/library/functions.html#round)

```python
print('Hi! Your change is {}'.format(round(change, 2)))
```

Sample case:

```
How much is your total bill?  555.677
How much is your payment?  1500
Hi! Your change is 944.323
Hi! Your change is 944.32
Hi! Your change is 944.32
```

Hope you learn and enjoyed the session! See you next time :)
