### ISSUE TITLE
Geo Pineda Exercise 1

### ISSUE THREAD

**Issue by imgeothegreat** [wwcodemanila/WWCodeManila-Python#56]
Operators 

https://github.com/geo1526/wwcode-python/blob/master/hello.py

**Comment by alyssonalvaran** [comment]
Great job! Just a few tips, though:

1. Avoid using x, y, and z as variable names. As much as possible, use variable names that are easy for other developers to comprehend like bill, payment, and change. ;)
2. When dealing with monetary values, use float instead of int to avoid problems with cents!

High five!
