### ISSUE TITLE
Challenge 1 Fajardo

### ISSUE THREAD

**Issue by Realkitten** [wwcodemanila/WWCodeManila-Python#61]
https://github.com/Realkitten/wwcode-python/blob/master/challenge.py

**Comment by alyssonalvaran** [comment]
Hi! It seems like there's a small mistake on line 3:
`a = bill - payment`
It should be:
`a = payment - bill`

And just a few tips:
1. Instead of using a as a variable name, use something that's easier to understand like change.
2. Use float instead of int so you can work on decimal values as well.

Anyway, you've done an amazing job. Congratulations! :)
